### ISSUE TITLE
语言切换没有反应

### ISSUE THREAD

**Issue by sunwhale** [greyli/todoism#1]
![screenshot from 2018-09-07 23-06-29](https://user-images.githubusercontent.com/6728539/45243205-36bdb700-b2f3-11e8-8e68-8be26a64a80e.png)
您好，我运行过程中点击简体中文后locale变量值已经更新，但页面没有变化仍然是英文，不知道是什么原因。

**Comment by greyli** [comment]
是不是没有生成MO文件？使用下面的命令：
```
$ flask translate compile
```

**Comment by sunwhale** [comment]
嗯嗯，多谢，生成MO文件以后正常运行了。

**Comment by sunwhale** [comment]
刚在书上看到后面时候发现这个命令了。

**Comment by greyli** [comment]
好的，不客气。
