### ISSUE TITLE
flask-restful

### ISSUE THREAD

**Issue by goodbad3** [greyli/todoism#10]
那位佬把这个todoism的api用flask-restful重写了，遇到了很大的kong难

**Comment by greyli** [comment]
先关闭了，这类问题发到 [HelloFlask 论坛](https://discuss.helloflask.com)或[交流群](http://helloflask.com#discuss)更容易获得回应。

**Comment by max3po** [comment]
只是换个扩展，参考文档，应该不至于这么难吧
