### ISSUE TITLE
作者您好，resources.py 中的AuthTokenAPI类中获取post的参数应该是request.args.get('grant_type')?

### ISSUE THREAD

**Issue by wangtaosecret** [greyli/todoism#2]
现在是
grant_type = request.form.get('grant_type')
username = request.form.get('username')
password = request.form.get('password')

这样好像是取不到参数值？作者大大对不对？

**Comment by greyli** [comment]
这里的几个值应该发送POST请求提供，所以要从`request.form`获取。书里面有相关描述，建议再重看一下相关内容。

**Comment by wangtaosecret** [comment]
好的，我再看看
