### ISSUE TITLE
time.clock被废弃了

### ISSUE THREAD

**Issue by paulzhn** [greyli/todoism#20]
`time.clock`从python3.3开始被废弃了，取而代之的是`time.perf_counter`

**Comment by greyli** [comment]
这个项目有用到 `time.clock` 吗？

**Comment by greyli** [comment]
先关闭了，问题没解决可以重开或继续评论。

**Comment by greyli** [comment]
偶然看到了相关问题，是 SQLAlchemy 内部的引用产生了错误，你可以试试升级 SQAlchemy 到最新版本。
