### ISSUE TITLE
mac osx 上 clone 本地 pipenv install --dev 报错

### ISSUE THREAD

**Issue by Hangyi** [greyli/todoism#3]
![196ed497-92b0-40ca-ba23-24a042cdf5ed 1](https://user-images.githubusercontent.com/11909598/46275211-bf481400-c58e-11e8-910c-1c6ac5a07255.jpg)

直接 clone 到本地的，想运行，结果这个报错了。貌似只适合windows的python2.7。
osx 上这个怎么解决，

**Comment by greyli** [comment]
那几个依赖是忽略掉的，不用在意。我在 Mac 上试了一下，没有出现报错。你可能是哪里没执行对？我看到你的图片里有虚拟环境已经激活的提示。

<img width="1014" alt="499615211277324564" src="https://user-images.githubusercontent.com/12967000/46276997-61b6c600-c594-11e8-91e4-23c69d661fd6.png">

**Comment by Hangyi** [comment]
谢谢作者，发现原因了，没有 `cd todoism` 。直接在 todoism 文件夹下，操作了。现在切换todoism 下的 todoism 后，再操作就行了
