### ISSUE TITLE
AttributeError: 'Babel' object has no attribute 'locale_selector_func'

### ISSUE THREAD

**Issue by aBlueBaby** [greyli/todoism#5]
AttributeError: 'Babel' object has no attribute 'locale_selector_func'
![image](https://user-images.githubusercontent.com/41498268/48144959-cc25f900-e2ec-11e8-8aaf-61d536aa3359.png)
请问这个是跟windows运行环境有关系吗？如何修正？盼复，谢谢。

**Comment by greyli** [comment]
应该和操作系统没关系。我看到你没有使用虚拟环境，请问项目依赖都安装了吗？

**Comment by aBlueBaby** [comment]
我用的pycharm缺省全局虚拟环境，依赖均已安装。看报错是获取系统参数失败，属性在package也能找到，是package的版本问题么？我的babel是直接下载的最新版的。

**Comment by greyli** [comment]
可以把 Babel 降级到 2.5.3 试一下。

**Comment by aBlueBaby** [comment]
我发现我用的是pip和全局virtualenv，教程上写的是pipenv,按教程上就可以了。

**Comment by greyli** [comment]
@aBlueBaby 好的
